### ISSUE TITLE
stop piping Twitter into #gratipay

### ISSUE THREAD

**Issue by chadwhitacre** [gratipay/roobot#64]
The amount of Twitter traffic on [`gratipay`](https://twitter.com/search?f=realtime&q=gratipay&src=typd) has become overwhelming to have piped into our main IRC channel, #gratipay. I propose that we start a second channel to collect public discussion of Gratipay, and redirect the Twitter stream there. That's also where we would pipe Google Alerts (https://github.com/gratipay/roobot/issues/63), and any other similar services we employ.

**Comment by whit537** [comment]
Hacked to turn it off: [IRC](https://botbot.me/freenode/gratipay/2015-01-20/?msg=30048551&page=2).

**Comment by Changaco** [comment]
I've moved the Twitter search to the #gratipay-stream channel.
